apiVersion: v1
kind: Service
metadata:
  name: ngp-sample-app-service
spec:
  selector:
    app: ngp-sample-app
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
    nodePort: 31803
  type: NodePort