# This is a basic workflow to help you get started with Actions

name: seal-secret
on:
  workflow_dispatch:
    inputs:
      secret_name:
        type: string
        required: true
      secret_environment:
        type: environment
        required: true
jobs:
  seal-secret:
    runs-on: macos-latest
    env:
      SECRET_ENVIRONMENT: ${{ github.event.inputs.secret_enrivonment }}
      SECRET_NAME: ${{ github.event.inputs.secret_name }}
    steps:
      - name: Install kubeseal
        uses: ConorMacBride/install-package@v1.0.0
        with:
          brew: kubeseal
      - name: Checkout local repository
        uses: actions/checkout@v3.0.0
        with:
          path: local
      - name: Base64 encode secret
        working-directory: ${{ github.workspace }}
        env:
          SECRET_STRING: ${{ secrets.${{ github.event.inputs.secret_name }} }}
        run: SECRET_BASE_64=$(echo $SECRET_STRING | base64)
      - name: Create secret YAML
        working-directory: ${{ github.workspace }}
        run: echo $SECRET_BASE_64
      #- name: Seal secret
        #working-directory: ${{ github.workspace }}/local
        #run: kubeseal --format YAML --cert public_encryption_key.pem <  > ../sealed-$1
        
